name: deploy-gh-pages

on:
  push:
    branches: [gh-pages, EDD-40]

jobs:
  deploy-gh-pages:
    # if: success() && github.ref == 'refs/heads/gh-pages'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Run build
      run: npm run build
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: dist
